### ISSUE TITLE
Need for Libraries API module?

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/libraries#1]
@quicksketch - I ported this module to Backdrop because views-slideshow needs it. I am wondering whether this is necessary in Backdrop. The description of Libraries API in drupal.org says

> > Drupal 7 only has built-in support for non-external libraries via hook_library(). But it is only suitable for drupal.org projects that bundle their own library; i.e., the module author is the creator and vendor of the library. Libraries API should be used for externally developed and distributed libraries. A simple example would be a third-party jQuery plugin. - https://www.drupal.org/project/libraries

Is this also the case for Backdrop?

Also, have we a recommended location for Libraries? I favour a folder /libraries rather than /sites/all/modules but is this OK?

**Comment by docwilmot** [comment]
see https://github.com/backdrop/backdrop-issues/issues/159

**Comment by Graham-72** [comment]
Thanks @docwilmot I had completely forgotten that discussion, and I should have found it before starting this issue. It looks like I should make my port an official release, for the time being at least, but first change where it has the libraries folder.

**Comment by quicksketch** [comment]
> It looks like I should make my port an official release, for the time being at least, but first change where it has the libraries folder.

Sounds like a plan @Graham-72. Let's keep the main discussion for core over in https://github.com/backdrop/backdrop-issues/issues/159.

**Comment by jenlampton** [comment]
Going to close this issue in favor of the other one. Thanks @Graham-72 for your work on libraries!
