### ISSUE TITLE
Remove "(deprecated)" frorm Libraries description

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/libraries#15]
This project is currently described as "deprecated" in multiple locations:

* README.md
* GitHub Description
* libraries.info

However, several projects depend on this one already. I've encountered this with Highcharts and Geshi Filter module. While projects that utilize GPL libraries are encouraged to bundle them into the related module project, some projects don't or can't, either because the license is not GPL or because they're depending on PHP libraries. Backdrop core's `hook_library_info()` only deals with JS/CSS libraries, not PHP ones.

It seems Libraries module still has a place for the foreseeable future. I think we should remove the scary "deprecated" warning throughout the project and update the README.md to better reflect the current state of things.

**Comment by ghost** [comment]
The current README says:

> If you have a use case that can't currently be solved without having to use Libraries API, then please file an issue to address that use case in Backdrop core: https://github.com/backdrop/backdrop-issues/issues/new/choose

So...?

**Comment by herbdool** [comment]
I agree. I was just updating Feeds and trying to figure out the best way to allow the SimplePie plugin be used. It's a BSD license which I'm not sure if it can be included in the module. I'd rather just let them use this module as one option.

**Comment by herbdool** [comment]
@quicksketch I created a PR to hopefully better explain to module developers when to use the other options and when this module might be required.

Currently this module has no maintainer, but perhaps we can agree in the dev meeting that this word change is preferable.
