### ISSUE TITLE
branch / version number confusion?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/libraries#3]
Did you port the 1.x branch of this module? It looks like Drupal is currently on 7.x-2.2, so if we need any of these features for Backdrop, we should port the 2.x branch, not 1.x.

I'm asking because the branch here in GitHub is named 1.x-1.x instead of 1.x-2.x, but the module I'm working on requires at least the 2.x version (in Drupal) so the backdrop set-up I'm starting with fails to meet requirements checks.  

Perhaps this is just a branch-name-issue and all the porting is fine as-is :)

**Comment by Graham-72** [comment]
Yes, I did port the 2.x branch and I should change the name of this branch to 1.x-2.x, but I cannot see how I can do this - perhaps someone with more permissions has to do it? The release is currently labelled 2.2.0 but I shall create a new release after dealing with this and also Issue #4.

I am very doubtful about the validity of this port to Backdrop. It contains functions from the Drupal version that are probably not relevant in Backdrop. I have it working with Views Slideshow ( which was my first need) and am currently trying to use it with a port of Juicebox, but am not yet successful with that.

**Comment by Graham-72** [comment]
I seem to have managed to create a branch 1.x-2.x.
