### ISSUE TITLE
Consider whether any changes on the Drupal version of 7.x-2.x should be ported

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/libraries#6]
I am beginning to port a module that lists v7.x-2.2 as a minimum and I think (correct me if I'm wrong) that you ported from 7.x-2.1. (Commits begin to diverge on Oct. 12, 2014).

I imported the Drupal libraries 7.x-2.x module to a [temporary Github repo](https://github.com/laryn/drupal_libraries/commits/7.x-2.x) for ease of [comparing](https://github.com/backdrop-contrib/libraries/commits/1.x-2.x).

**Comment by Graham-72** [comment]
It is my understanding that I ported this from 7.x-2.2 but perhaps I need to do a thorough check, particularly now that Drupal is on 7.x-2.3

**Comment by Graham-72** [comment]
@laryn does this record of history help?

![libraries_history1](https://cloud.githubusercontent.com/assets/10559274/18030029/d09270aa-6ca0-11e6-8943-06390e8c1b89.png)

**Comment by laryn** [comment]
@Graham-72 Oh, you may be right about that. I see it now on the release notes, too. So my problem in porting is probably unrelated to this module. Sorry! 😬
