### ISSUE TITLE
Variant not detected

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/libraries#7]
Please see my library definition here: https://github.com/backdrop-contrib/views_slideshow_cycle2/blob/new/views_slideshow_cycle2.module#L7

If I only have jquery.cycle2.min.js and not jquery.cycle2.js available, the library isn't detected, even though the minified version is setup as a variant.

It seems to be because in `libraries_detect()` it checks the version before it checks any variants. This means `libraries_detect()` returns an error for my library.

Am I doing something wrong, or does Libraries have a bug?

**Comment by Graham-72** [comment]
@BWPanda do you think there is any point in having the cycle2 library included via the Libraries module, rather than include it in the views_slideshow_cycle2 module? The reason I ask is that the Libraries module seems over-complicated and probably does contain bugs. Some while ago there was a discussion around this general topic in https://github.com/backdrop/backdrop-issues/issues/159.

**Comment by ghost** [comment]
I like the idea of including libraries in modules directly, but I don't think Views Slideshow Cycle2 (VSC2) is a good candidate for that, as it's too specific for Views/Views Slideshow. I toyed with the idea of creating a separate module for Cycle2 where the library could be included directly (and then maybe use Cycle2 as a field formatter, etc.), and then depend on that in VSC2, but in the end I decided to simply remove the ability to use either the production (minified) or development (source) versions and instead just support production (minified) versions of the Cycle2 library. This greatly simplified the Libraries code, so that's solved my problem for now.

But there is still that issue with Libraries, so maybe if/when it's included in core or updated then that can be addressed.

**Comment by Graham-72** [comment]
@BWPanda I didn't mean that the Libraries module should be included in Views Slideshow Cycle 2 but rather that the javascript library for Cycle2 could be there. An example of this approach might be the Flexslider contrib module which includes the Flexslider library.

**Comment by ghost** [comment]
> I didn't mean that the Libraries module should be included in Views Slideshow Cycle 2...

Neither did I. I meant the Cycle2 library (lowercase 'L').

**Comment by ghost** [comment]
Closing as Libraries API is deprecated and won't receive any more updates.
