### ISSUE TITLE
Use of undefined constant DRUSH_BOOTSTRAP_BACKDROP_FULL

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/libraries#8]
I get the following warning on my site:

> Use of undefined constant DRUSH_BOOTSTRAP_BACKDROP_FULL - assumed 'DRUSH_BOOTSTRAP_BACKDROP_FULL' (this will throw an Error in a future version of PHP) libraries.drush.inc:15

**Comment by opi** [comment]
Better use `DRUSH_BOOTSTRAP_DRUPAL_FULL` maybe, or even `BackdropBoot::BOOTSTRAP_FULL` from https://github.com/backdrop-contrib/drush/blob/1.x-0.x/BackdropBoot.php

Ask @serundeputy for his Backdrop & Drush Fu ;)

**Comment by klonos** [comment]
Yeah not 100% sure either, but I could not find any references of `DRUSH_BOOTSTRAP_DRUPAL_FULL`. I found `BACKDROP_BOOTSTRAP_FULL` though (untested).

**Comment by ghost** [comment]
Hmm, ok, I'll do some testing...

**Comment by herbdool** [comment]
I recall in a different module that we changed it to `BackdropBoot::BOOTSTRAP_FULL`

**Comment by ghost** [comment]
Closing as Libraries API is deprecated and won't receive any more updates.
